poopreporter/urls.py
from django.conf.urls import patterns, include, url
from django.shortcuts import redirect

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),

    url(r'^$', 'poopreporter.views.index'),
    url(r'^about$', 'poopreporter.views.about'),
    url(r'^team$', 'poopreporter.views.team'),
    url(r'^contact$', 'poopreporter.views.contact'),


    url(r'^statuses$', 'poopreporter.json_data.statuses'),
    url(r'^symptoms$', 'poopreporter.json_data.symptoms'),
    url(r'^data$', 'poopreporter.json_data.statuses_and_symptoms'),
    url(r'^favicon\.ico$', 'redirect',
        {'url': '/static/images/favicon.ico'}),

    url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'template_name': 'logout.html'}),
    url(r'^accounts/profile/$', 'poopreporter.views.profile' ),
    url(r'^accounts/register/$', 'poopreporter.views.register' ),
    
    url(r'^episode/(?P<id>[^/]*)/$', 'poopreporter.views.episode' ),
    url(r'^input/$', 'poopreporter.views.input' ),
    url(r'^updatesymptoms/(?P<id>[^/]*)/$', 'poopreporter.views.updateSymptoms' ),
    url(r'^addcomment/(?P<id>[^/]*)/$', 'poopreporter.views.addComment' ),
    
    
    url(r'', include('social_auth.urls')),
)

poopreporter/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timesince

from datetime import *

class Symptom(models.Model):
    name = models.CharField(max_length=200)
    
class Stuff(models.Model):
    name = models.CharField(max_length=200)

class Episode(models.Model):
    user = models.ForeignKey(User, related_name='+')
    started = models.DateTimeField(auto_now=True, auto_now_add=True)
    ended = models.DateTimeField(blank=True, null=True)
    wishlist = models.ManyToManyField(Stuff)
    zipcode = models.CharField(max_length=20)
    
    def description(self):
        updates = Update.objects.select_related("episode").filter(episode=self)
        symptom_set = set()
        for update in updates:
            for symptom in update.symptoms.all():
                symptom_set.add(symptom.name)
        return ", ".join(symptom_set)
        
    def duration(self): 
        if self.ended == None:
            ts = self.started- self.started
            days = ts.days + 1
            return "%d days" % days
        else:
            print timesince(self.started, self.ended)
            days = ts.days + 1
            return "%d days" % days
            
    def status(self):
        user_comment = LoggedInComment.objects.select_related("episode").filter(episode=self).order_by("time")[0]
        return user_comment.text
        
    
class Update(models.Model):
    time = models.DateTimeField(auto_now=True, auto_now_add=True)
    symptoms = models.ManyToManyField(Symptom)
    episode = models.ForeignKey(Episode)
    
class LoggedInComment(models.Model):
    user = models.ForeignKey(User, related_name='+')
    time = models.DateTimeField(auto_now=True, auto_now_add=True)
    text = models.CharField(max_length=1000)
    episode = models.ForeignKey(Episode)
    



    
    

templates/about.html
{% extends 'base.html' %}
{% block title %}About PoorMe{% endblock %}
{% block headerext %}
<div class="bigbutton"><a href="/input" class="buttonlink">I'm Sick</a></div>
{% endblock %}
{% block content %}

<h2>Welcome to PoorMe!</h2>
<p>
PoorMe is a web (and soon mobile) app that puts the "Public" back in Public Health!  For common, preventable illnesses including influenza, the common cold, and foodborne disease, many people don't report their symptoms to a doctor and are therefore invisible to the public health organizations charged with preventing disease and stopping outbreaks.</p><br>
<p>
As a result, outbreak investigations and estimates of disease burden are delayed and inefficient. This means more illness and lost productivity in our communities. PoorMe aims to solve this problem.</p><br>
<p>
We are creating an app where it is easy for people to take care of themselves, their loved ones, and their communities.  PoorMe users can: </p><br>
<ol>
<li>Share symptoms anonymously and contribute to real time data. This data is in-turn displayed on a map showing who's sick and where, in your area.</li>
<li>Connect with other sick friends -- might we suggest offering advice, sympathy, empathy or stories.</li>
<li>Support local businesses through one-click delivery of goodies like soup, a free dog-walk, or anything else that will make your sick friends' lives easier.</li></ol><br>
<p>
PoorMe started as a project at <a href="http://www.startupweekend.org">Startup Weekend</a> where 6 individuals met for the first time and bonded over a common interest in crowd-sourcing public health data. Over the ensuing 48 hours, we built this site!</p><br>
<p>
Feel free to reach out with any questions, comments, concerns, bugs, or any other feedback -- kdb26 at uw.edu</p><br>

{% endblock %}

templates/base.html
{% load staticfiles %}
<!doctype html>
<html>
  <head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static "css/main.css" %}" type="text/css" />
    <link href='http://fonts.googleapis.com/css?family=Nunito:400,700,300' rel='stylesheet' type='text/css'>
    <script src="{% static "javascripts/jquery-1.9.0.min.js" %}"></script>
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-38056362-1']);
      _gaq.push(['_trackPageview']);
      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>

    <meta name="viewport" content="width=device-width/" >
    {% block jsext %}{% endblock %}
  </head>
  <body>

    {% if user.is_authenticated %}
        <div id="outertopbar"><div id="innertopbar">Logged in as <a href="/accounts/profile">{{ user.first_name }} {{ user.last_name }}</a>!  <a href="{% url 'django.contrib.auth.views.logout' %}">Logout</a> </div></div>
    {% else %}
        <div id="outertopbar"><div id="innertopbar"><a href="/login/facebook"><img src="{% static "images/facebook_login_button.png" %}"></a></div></div>
    {% endif %}

    <div id="outerheader"><div id="innerheader">
      <a href="/"><img alt="logo" src="{% static "images/logo.png" %}" class="align-left"></a>
      {% block headerext %}
      {% endblock %}
      <div id="nav">
        <ul>
          <li><a href="/" id="{{homeclass}}">Home</a></li>
          <li><a href="/about" id="{{aboutclass}}">About</a></li>
          <li><a href="/team" id="{{teamclass}}">Team</a></li>
          <li><a href="/contact" id="{{contactclass}}">Contact</a></li>
          <!-- li><input type="text" onfocus="this.value=''" value="Search" class="searchbox"></li -->
        </ul>
      </div>      
    </div></div>
    <div class="clearfix"></div>
    <div id="content">
      {% block content %}{% endblock %}
    </div>
    <div id="outerfooter"><div id="innerfooter">Copyright 2013 - TeamDookie</div></div>
  </body>
</html>

templates/communication.html
{% extends 'base.html' %}
{% block title %}Poor Me - Communication{% endblock %}
{% block jsext %}
<script type="text/javascript">
  $(document).ready(function() {
  });
</script>
{% endblock %}
{% block headerext %}
<div class="bigbutton"><a href="/input" class="buttonlink">I'm Sick</a></div>
{% endblock %}
{% block content %}
<div id="sidebar">
  <div class="personname">{{status.name}}</div>
  <div class="comment">"{{status.status.text}}"</div>
  {% if wishlist.count > 0 %}
  <div>Wishlist</div>
  <ul>
    {% for w in wishlist.all %}
    <li>{{w.name}}</li>
    {% endfor %}
  </ul>
  {% endif %}
</div>
<div id="maincol">
  {% if replies.count == 0 %}
  <div style="height: 2em; font-style: italic">Be the first to leave a reply to {{status.name}}</div>
  {% else %}
  {% for r in replies.all %}
  <div class="commentbox">
    <div class="comment">"{{r.text}}"</div>
    <div class="signature">- {{r.author}}</div>
    <div class="clearfix"></div>
    <hr>
  </div>
  {% endfor %}
  {% endif %}
  <div>
    <form action="/communication/{{status.id}}" method="post">{% csrf_token %}
    <div>Comment</div>
    <textarea name="text" cols="40" rows="8"></textarea>
    {% if wishlist.count > 0 %}
    <div>Send the following to {{status.name}}</div>
    <ul style="list-style: none">
      {% for w in wishlist.all %}
      <li><input type="checkbox">{{w.name}}</li>
      {% endfor %}
    </ul>
    {% endif %}

    <div>Name</div>
    <div><input name="author" type="text"> <input type="submit" value="Submit"></div>
    </form>
  </div>
</div>
{% endblock %}

templates/contact.html
{% extends 'base.html' %}
{% block title %}PoorMe - Contact{% endblock %}
{% block headerext %}
<div class="bigbutton"><a href="/input" class="buttonlink">I'm Sick</a></div>
{% endblock %}
{% block content %}
<h3>Contact</h3>

<p>
<b>General questions:</b> Karlyn at kdb26 at uw.edu, Twitter: @KarlynBeer
</p><p>
<b>Site / bugs / technical issues:</b> <a href="mailto:poorme@googlegroups.com">poorme@googlegroups.com</a>
</p>
{% endblock %}

templates/episode.html
{% extends "base.html" %}


{% block content %}

<script type="text/javascript">
    function showForm(){
        $('#updatesymptoms').toggle();
    }
</script>

{% if user.is_authenticated and user == episode.user %}
    <div id="privatediv">
    <p>Only you can see this box with your symptoms:</p>
    
        <div class="bigbuttonprofile"  onclick="showForm()"><a href="#" class="buttonlink"></a>Update Symptoms</a></div>

    <p>
    {% for u in updates %}
    
        <br />
        <i>{{ u.time }}</i>
        <ul style="padding-left: 30px;">
        {% for s in u.symptoms.all %}
            <li>{{ s.name }}</li>
        {% endfor %}    
        </ul>
    {% endfor %}
    
    <div id="updatesymptoms">
        <div class="whatswrong">How are you feeling now ?</div>
        <form method="post" action="/updatesymptoms/{{id}}">
        {% csrf_token %}
        
        {% for field in form %}
            {{ field }}
        {% endfor %}
    
        <input type="submit" value="update" />

        </form>
    </div>

    </div>
{% endif %}
<br />
<br />

<div id="publicdiv" style="background-color: white; border: 1px solid black; padding: 10px;">

{% if user.is_authenticated %}
<div>
Anyone can see the contents of this box.
<br />
</div>
{% endif %}

<div id="sidebar">
  <div class="personname">{{name}}</div>
  <div class="comment">"{{status}}"</div>
  {% if wishlist.count > 0 %}
  <div id="wishlist">
  <h4>Wishlist</h4>
  <ul style="padding-left: 30px;">
    {% for w in wishlist.all %}
    <li>{{w.name}}</li>
    {% endfor %}
  </ul>
  </div>
  {% endif %}
  
</div>

{% if user.is_authenticated and user == episode.user %}
<div class="bigbuttonprofile"><a href="https://www.facebook.com/dialog/feed?
  app_id=330449400388404&
  link=http://poorme.co/episode/{{episode.id}}/&
  picture=http://poorme.co/static/images/logo.png&
  name=Poor {{name}} is sick!&
  caption={{status}}&
  description=Your friend isn't feeling well and is using PoorMe to track their symptoms. Find out how you can help them feel better!&
  redirect_uri=http://poorme.co/episode/{{episode.id}}" class="buttonlink">Post to Facebook</a></div>
  {% endif %}

<div id="maincol">
  {% if comments.count == 0 %}
  <div style="height: 2em; font-style: italic">Be the first to leave a reply to {{status.name}}</div>
  {% else %}
  {% for r in comments.all %}
  <div class="commentbox">
    <div class="comment">"{{r.text}}"</div>
    <div class="signature">- {{r.user.first_name}}</div>
    <div class="clearfix"></div>
    <hr>
  </div>
  {% endfor %}
  {% endif %}
  
  <div>
    {% if user.is_authenticated %}
      <form action="/addcomment/{{id}}/" method="post">{% csrf_token %}
      <div>Commenting as {{user.first_name}}</div>
      {{ comment_form.text }}
      {% if wishlist.count > 0 %}
      <div>Send the following to {{name}}</div>
      <ul style="list-style: none">
        {% for w in wishlist.all %}
        <li><input type="checkbox"> {{w.name}}</li>
        {% endfor %}
      </ul>
      {% endif %}

      <div> <input type="submit" value="Submit"></div>
      </form>
    {% else %}
    <a href="/login/facebook"><h2>Sign in to leave a reply</h2></a>
    {% endif %}
  </div>


  <div style="clear: both;"></div>
        
</div>

</div>
   
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}PoorMe - Welcome{% endblock %}
{% block jsext %}
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDN1P_EGMeYDtgzg22HindpmcRnNr_zEv8&sensor=true&libraries=visualization"></script>
  <script type="text/javascript" src="http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/src/markerclusterer_compiled.js"></script>
  <script src="{% static "javascripts/clustermap.js" %}"></script>

<script type="text/javascript">
  $(document).ready(function() {
        $.getJSON('/data', function(data){
            initialize(data);
            populateChecklist(data.symptom_list);
        });
        
  });
</script>
{% block headerext %}
  {% if user.is_authenticated %}
    <div class="bigbutton"><a href="/input" class="buttonlink">I'm Sick</a></div>
  {% else %}
    <div class="bigbutton"><a href="/login/facebook?next=/input" class="buttonlink">I'm Sick</a></div>
  {% endif %}
{% endblock %}
{% endblock %}
{% block content %}

    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=330449400388404";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>

  <div id="explanation">
  Public health data is really valuable, but hard to come by. You can help by sharing your symptoms when you're sick. 
  </div>
  

  <br />
  <div class="whatswrong" id="map_title">
  People Sick in <span id="cityName">Seattle</span>
  </div>

  <div id="map_canvas" style="width:100%; height:400px; border: 1px solid black;"></div>
  <br />  
  
  <div id="map_options">
    <a href="#" onclick="showPeople()">Your Friends</a> | 
    <a href="#" onclick="showSymptoms()">Trending Symptoms</a>
  </div>
  
  <div id="symptom_checklist">
    <br />
    <div class="whatswrong">Symptoms</div>
  </div>
  
  <br>

  <div class="socialmedia">
      <a href="https://twitter.com/share" class="twitter-share-button">Tweet</a>
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

      <div class="fb-like" data-href="http://poorme.co/" data-send="true" data-width="450" data-show-faces="false"></div>

      <!-- Place this tag where you want the share button to render. -->
      <div class="g-plus" data-action="share"></div>

      <!-- Place this tag after the last share tag. -->
      <script type="text/javascript">
        (function() {
          var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
          po.src = 'https://apis.google.com/js/plusone.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
        })();
      </script>
  </div>

  <div>
<a class="twitter-timeline" data-dnt="true" href="https://twitter.com/search?q=%23FoodSafety+OR+%23MMWR+OR+from%3AWA_DeptofHealth+OR+from%3AFoodsafetynews+OR+from%3AProMED_mail+OR+from%3AMappyHealth+OR+from%3AHealthmap+OR+from%3AFluNearYou+OR+from%3ACIDRAP+OR+from%3AISB.USA+OR+from%3AUSDAFoodSafety" data-widget-id="333329690624397313">Tweets about "#FoodSafety OR #MMWR OR from:WA_DeptofHealth OR from:Foodsafetynews OR from:ProMED_mail OR from:MappyHealth OR from:Healthmap OR from:FluNearYou OR from:CIDRAP OR from:ISB.USA OR from:USDAFoodSafety"</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </div>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block content %}

{% if user.is_authenticated %}
    <p>Logged in as <a href="/accounts/profile/">{{ user.username }}</a></p>
{% else %}


    {% if false %}
        {% if form.errors %}
        <p>Your username and password didn't match. Please try again.</p>
        {% endif %}
        
        <form method="post" action="{% url 'django.contrib.auth.views.login' %}">
        {% csrf_token %}
        <table>
        <tr>
            <td>{{ form.username.label_tag }}</td>
            <td>{{ form.username }}</td>
        </tr>
        <tr>
            <td>{{ form.password.label_tag }}</td>
            <td>{{ form.password }}</td>
        </tr>
        </table>
        
        <input type="submit" value="login" />
        <input type="hidden" name="next" value="{{ next }}" />
        </form>
        
    {% else %}
        <p><a href="/login/facebook">Log in with your Facebook account</a></p>
    {% endif %}

{% endif %}


{% endblock %}

templates/logout.html
{% extends "base.html" %}

{% block content %}

You have successfully logged out.

{% endblock %}

templates/profile.html
{% extends "base.html" %}

{% block content %}

<img src="{{ profile_pic }}" />

{% if user.is_authenticated %}

    <div class="bigbuttonprofile"><a href="/input" class="buttonlink">I'm Sick</a></div>

    <p>Welcome, {{ user.first_name }} {{ user.last_name }}!</p>

    
    <p>
    <h2>Past times you've been sick:</h2>
    {% for i in episodes %}
        <h4><a href="/episode/{{ i.id }}">{{ i.started|timesince }} ago ({{ i.started|date:"M d, Y" }})</a></h4>
        <h4>{{ i.description }}</h4>
        <hr />
    {% endfor %}
    </p>
    
    
    
{% else %}
    <p>Welcome, new user. Please log in.</p>
{% endif %}

{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block content %}


<form action="{% url 'poopreporter.views.register' %}" method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>

{% endblock %}

templates/sick.html
{% extends 'base.html' %}
{% block title %}PoorMe - Input{% endblock %}
{% block jsext %}
<script type="text/javascript">
  $(document).ready(function() {
    $('#anonymous').click(function() {
      if ($(this).is(':checked')) {
        $('#nameinput').prop('value', 'anonymous');
      } else {
        $('#nameinput').prop('value', '');
      }
      $('#nameinput').prop('disabled', $(this).is(':checked'));
    });

    $.ajax({
      type: "GET",
      url: "http://api.ipinfodb.com/v3/ip-city/?key=139a60d81999b3025d9fc13d412ae7f3997ff110cace95b1505fb72258aaef64&format=json",
      dataType: "jsonp",
      success: fillInZip
    });
  });

  function fillInZip(data){
      console.log("fill in zip ", data);
      $("#id_zipcode").val(data.zipCode);
  }
</script>
{% endblock %}
{% block content %}


<div id="inputarea">
  <form action="/input/" method="post" id="illnessForm">{% csrf_token %}
  <div id="left">
        <div class="inputrow"><span class="caption" id="namecaption">Name</span> {{ user.first_name }}</div>
        <!--<div class="inputrow"><input name="anonymous" id="anonymous" type="checkbox"><span>hide from map</span></div> -->
        <div class="inputrow"><span class="caption">Status</span></div>
        {% if text_errors %}
        {{text_errors}}
        {% endif %}
        
        <div class="inputrow">{{ text_form.text }} </div> 
        
        <div class="inputrow"><span class="caption">Zip</span></div>
        {% if episode_errors %}
            {{episode_errors}}
        {% endif %}
        <div class="inputrow">{{ episode_form.zipcode }}</div>   
  </div>
  <div id="right">
  
    <div class="whatswrong">What's wrong ?</div>
    {% if update_errors %}
        {{update_errors}}
    {% endif %}
    {{ update_form.symptoms }}
  </div>
  
  <div class="clearfix" style="height: 2em;"></div>

    <div id="submitbar"><input type="submit" value="Save symptoms and status"></div>
  </form>
</div>
{% endblock %}

templates/team.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}PoorMe - Our Team{% endblock %}
{% block headerext %}
<div class="bigbutton"><a href="/input" class="buttonlink">I'm Sick</a></div>
{% endblock %}
{% block content %}
<img src="{% static "images/teamdookie.jpg" %}" style="border: 0">
<h3>Bios</h3>
<p>
<b>Karlyn Beer</b> holds a MS in epidemiology from UW School of Public Health and is a current PhD candidate in the Molecular and Cellular Biology program at UW and Institute for Systems Biology.  Contact Karlyn at kdb26 @ uw.edu for more information, collaborations and site suggestions/updates. Twitter @KarlynBeer
</p>
<br>
<p>
<b>Kathleen Tuite</b> is a PhD student in Computer Science at the University
of Washington. She is part of the Graphics and Vision lab GRAIL as
well as the Center for Game Science, where she worked on the games
Fold It and PhotoCity. She is passionate about enabling the crowd to
contribute data in a way that adds up.
</p>
<br>
<p>
<b>Brian Reyes</b> is a User Experience Designer working for PitchBook Data, Inc.  He also contributes to several small projects via <a href="www.bcr-design.com">www.bcr-design.com</a>.  He enjoys building websites and applications that are fun and easy to use.
</p>
<br>
<p>
<b>Matt Decuir</b> is an aspiring programmer with a background in analytics.  He spent the last 6 months travelling the world and is looking forward to moving to Minneapolis to be closer to his girlfriend.
</p>
<br>
<p>
<b>Wei-ju Wu</b> is a german software engineer at the Institute for Systems Biology. He studied computer science and biochemistry at the Free University and Humboldt-University in Berlin. He is driven by the desire to create software that helps researchers fighting diseases and benefit society.
</p>

<h3>Quotes</h3>
<div><span class="quote">"I think I'm getting the black lung, pop"</span> -- Brian, Designer</div>
<div><span class="quote">"Log odds + odd logs: poop for public health since 2013"</span> -- Karlyn, Team Lead</div>
<div><span class="quote">"bathroom: KEEP OUT"</span> -- Lisa, Project Manager</div>
<div><span class="quote">"You read my diarrhea!?"</span> -- Kathleen, Developer</div>
<div><span class="quote">"I don't always get sick, but when I do, I drink dos equis"</span> -- Matt, Customer Development</div>
<div><span class="quote">"while(seattle.rain==true) get(sick)"</span> -- Wei-Ju, Developer</div>
{% endblock %}